Feature/exercicio 9
annecaselato/helpper-origins-exercicio-9 pull request #1
Opened 2021-11-20 16:15 UTC by annecaselato

2021-11-20 16:16 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 9](https://trello.com/c/TrbuoR44/286-exerc%C3%ADcio-9)

2021-11-20 18:18 UTC, ErickHelpper requested changes

2021-11-20 18:18 UTC, ErickHelpper commented on src/modules/users/v1/controllers/ClientController.ts
> +     *     parameters:
Aqui nos parameters seria só o clientId

2021-11-20 18:18 UTC, ErickHelpper commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +                options: [['Ativo', 'Inativo']]
Aqui daria pra implementar o mesmo enum que eu comentei lá em cima.

2021-11-22 23:09 UTC, ErickHelpper approved these changes

2021-11-22 23:10 UTC, merged